<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MajorRecommendation;

class MajorRecommendationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data berdasarkan Keputusan Menteri Pendidikan Dasar dan Menengah Republik Indonesia 
        // Nomor 102/M/2025 tentang Mata Pelajaran Pendukung Program Studi dalam Seleksi Nasional Berdasarkan Prestasi

        $majors = [
            // RUMPUN ILMU: HUMANIORA
            [
                'major_name' => 'Seni',
                'description' => 'Program studi seni meliputi berbagai bidang seni seperti seni rupa, seni musik, seni tari, dan seni teater.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Seni Budaya'],
                'preferred_subjects' => ['Seni Budaya'],
                'career_prospects' => 'Seniman, Kurator, Pengajar Seni, Desainer Grafis, Musisi, Koreografer',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sejarah',
                'description' => 'Program studi yang mempelajari peristiwa masa lalu dan pengaruhnya terhadap masa kini.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sejarah'],
                'preferred_subjects' => ['Sejarah Indonesia'],
                'career_prospects' => 'Sejarawan, Peneliti, Pengajar, Penulis, Kurator Museum',
                'is_active' => true,
            ],
            [
                'major_name' => 'Linguistik',
                'description' => 'Program studi yang mempelajari bahasa dan strukturnya secara ilmiah.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Bahasa Indonesia Tingkat Lanjut', 'Bahasa Inggris'],
                'preferred_subjects' => ['Bahasa Indonesia', 'Bahasa Inggris'],
                'career_prospects' => 'Ahli Bahasa, Penerjemah, Editor, Peneliti Bahasa, Konsultan Bahasa',
                'is_active' => true,
            ],
            [
                'major_name' => 'Susastra/Sastra',
                'description' => 'Program studi yang mempelajari karya sastra dan bahasa dalam konteks budaya.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Bahasa Indonesia Tingkat Lanjut'],
                'preferred_subjects' => ['Bahasa Indonesia', 'Bahasa Asing'],
                'career_prospects' => 'Sastrawan, Penulis, Editor, Kritikus Sastra, Pengajar Bahasa',
                'is_active' => true,
            ],
            [
                'major_name' => 'Filsafat',
                'description' => 'Program studi yang mempelajari pemikiran mendalam tentang hakikat kehidupan dan pengetahuan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi'],
                'preferred_subjects' => ['Sejarah Indonesia', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Filsuf, Peneliti, Pengajar, Konsultan, Penulis',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU SOSIAL
            [
                'major_name' => 'Sosial',
                'description' => 'Program studi yang mempelajari interaksi sosial dan struktur masyarakat.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi'],
                'preferred_subjects' => ['Sejarah Indonesia', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Sosiolog, Peneliti Sosial, Konsultan, Pengajar, Aktivis',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ekonomi',
                'description' => 'Program studi yang mempelajari produksi, distribusi, dan konsumsi barang dan jasa.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi', 'Matematika'],
                'preferred_subjects' => ['Ekonomi', 'Matematika'],
                'career_prospects' => 'Ekonom, Analis Ekonomi, Konsultan, Peneliti, Pengajar',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU ALAM
            [
                'major_name' => 'Pertahanan',
                'description' => 'Program studi yang mempelajari strategi dan sistem pertahanan negara.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Pendidikan Pancasila'],
                'preferred_subjects' => ['PPKn'],
                'career_prospects' => 'Ahli Pertahanan, Analis Keamanan, Konsultan Pertahanan, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Psikologi',
                'description' => 'Program studi yang mempelajari perilaku dan proses mental manusia.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi', 'Matematika'],
                'preferred_subjects' => ['Matematika', 'Sosiologi'],
                'career_prospects' => 'Psikolog, Konselor, Peneliti, HRD, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kimia',
                'description' => 'Program studi yang mempelajari komposisi, struktur, dan sifat materi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Kimia'],
                'preferred_subjects' => ['Kimia'],
                'career_prospects' => 'Ahli Kimia, Peneliti, Quality Control, Pengajar, Konsultan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Kebumian',
                'description' => 'Program studi yang mempelajari bumi dan fenomena alam yang terjadi di dalamnya.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Fisika', 'Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Fisika', 'Matematika', 'Geografi'],
                'career_prospects' => 'Geolog, Geofisikawan, Peneliti, Konsultan Lingkungan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Kelautan',
                'description' => 'Program studi yang mempelajari ekosistem laut dan sumber daya kelautan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi', 'Geografi'],
                'career_prospects' => 'Ahli Kelautan, Peneliti, Konsultan Lingkungan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Biologi',
                'description' => 'Program studi yang mempelajari makhluk hidup dan proses kehidupan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Biologi, Peneliti, Konsultan Lingkungan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Biofisika',
                'description' => 'Program studi yang mempelajari aplikasi prinsip fisika dalam sistem biologis.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Fisika'],
                'preferred_subjects' => ['Fisika'],
                'career_prospects' => 'Ahli Biofisika, Peneliti, Konsultan Medis, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Fisika',
                'description' => 'Program studi yang mempelajari materi, energi, dan interaksi antar keduanya.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Fisika'],
                'preferred_subjects' => ['Fisika'],
                'career_prospects' => 'Fisikawan, Peneliti, Konsultan, Pengajar, Engineer',
                'is_active' => true,
            ],
            [
                'major_name' => 'Astronomi',
                'description' => 'Program studi yang mempelajari benda-benda langit dan fenomena luar angkasa.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Fisika', 'Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Fisika', 'Matematika'],
                'career_prospects' => 'Astronom, Peneliti, Pengajar, Konsultan',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU FORMAL
            [
                'major_name' => 'Komputer',
                'description' => 'Program studi yang mempelajari pengembangan sistem komputer dan teknologi informasi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Programmer, Software Engineer, Data Scientist, IT Consultant',
                'is_active' => true,
            ],
            [
                'major_name' => 'Logika',
                'description' => 'Program studi yang mempelajari prinsip penalaran dan argumentasi yang valid.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Logikawan, Peneliti, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Matematika',
                'description' => 'Program studi yang mempelajari angka, kuantitas, struktur, dan perubahan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Matematikawan, Peneliti, Aktuaris, Konsultan, Pengajar',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU TERAPAN
            [
                'major_name' => 'Ilmu Pertanian',
                'description' => 'Program studi yang mempelajari teknologi dan manajemen pertanian modern.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Pertanian, Peneliti, Konsultan Pertanian, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Peternakan',
                'description' => 'Program studi yang mempelajari pemeliharaan dan pengembangan ternak.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Peternakan, Peneliti, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Perikanan',
                'description' => 'Program studi yang mempelajari pengelolaan sumber daya perikanan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Perikanan, Peneliti, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Arsitektur',
                'description' => 'Program studi yang mempelajari perancangan bangunan dan lingkungan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika', 'Fisika'],
                'preferred_subjects' => ['Matematika', 'Fisika'],
                'career_prospects' => 'Arsitek, Konsultan, Pengajar, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Perencanaan Wilayah',
                'description' => 'Program studi yang mempelajari perencanaan tata ruang dan pembangunan wilayah.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi', 'Matematika'],
                'preferred_subjects' => ['Ekonomi', 'Matematika'],
                'career_prospects' => 'Perencana Wilayah, Konsultan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Desain',
                'description' => 'Program studi yang mempelajari perancangan visual dan produk kreatif.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Seni Budaya', 'Matematika'],
                'preferred_subjects' => ['Seni Budaya', 'Matematika'],
                'career_prospects' => 'Desainer, Art Director, Konsultan Desain, Pengajar',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU SOSIAL (Lanjutan)
            [
                'major_name' => 'Akuntansi',
                'description' => 'Program studi yang mempelajari pencatatan dan pelaporan keuangan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi'],
                'preferred_subjects' => ['Matematika', 'Ekonomi'],
                'career_prospects' => 'Akuntan, Auditor, Konsultan Keuangan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Manajemen',
                'description' => 'Program studi yang mempelajari pengelolaan organisasi dan sumber daya.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi'],
                'preferred_subjects' => ['Matematika', 'Ekonomi'],
                'career_prospects' => 'Manajer, Konsultan Bisnis, Entrepreneur, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Logistik',
                'description' => 'Program studi yang mempelajari pengelolaan rantai pasok dan distribusi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi'],
                'preferred_subjects' => ['Matematika', 'Ekonomi'],
                'career_prospects' => 'Ahli Logistik, Supply Chain Manager, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Administrasi Bisnis',
                'description' => 'Program studi yang mempelajari pengelolaan administrasi dalam konteks bisnis.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi'],
                'preferred_subjects' => ['Matematika', 'Ekonomi'],
                'career_prospects' => 'Administrator, Manajer, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Bisnis',
                'description' => 'Program studi yang mempelajari aspek-aspek operasional dan strategis bisnis.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi'],
                'preferred_subjects' => ['Matematika', 'Ekonomi'],
                'career_prospects' => 'Entrepreneur, Manajer, Konsultan Bisnis, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Komunikasi',
                'description' => 'Program studi yang mempelajari proses komunikasi dan media.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi', 'Antropologi'],
                'preferred_subjects' => ['Bahasa Indonesia', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Jurnalis, PR, Content Creator, Konsultan Komunikasi',
                'is_active' => true,
            ],
            [
                'major_name' => 'Pendidikan',
                'description' => 'Program studi yang mempersiapkan calon pendidik dan tenaga kependidikan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Mata Pelajaran Pendukung yang Relevan'],
                'preferred_subjects' => ['Mata Pelajaran Pendukung yang Relevan'],
                'career_prospects' => 'Guru, Dosen, Konsultan Pendidikan, Peneliti Pendidikan',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU ALAM (Lanjutan)
            [
                'major_name' => 'Teknik/Rekayasa',
                'description' => 'Program studi yang mempelajari aplikasi ilmu pengetahuan untuk memecahkan masalah teknis.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Fisika', 'Kimia', 'Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Fisika', 'Kimia', 'Matematika'],
                'career_prospects' => 'Engineer, Konsultan Teknik, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Lingkungan',
                'description' => 'Program studi yang mempelajari interaksi manusia dengan lingkungan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Lingkungan, Konsultan Lingkungan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kehutanan',
                'description' => 'Program studi yang mempelajari pengelolaan hutan dan sumber daya hutan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Kehutanan, Konsultan Lingkungan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Kedokteran',
                'description' => 'Program studi yang mempelajari diagnosis, pengobatan, dan pencegahan penyakit.',
                'min_score' => 80.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Kimia'],
                'preferred_subjects' => ['Biologi', 'Kimia'],
                'career_prospects' => 'Dokter, Peneliti Medis, Konsultan Kesehatan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Kedokteran Gigi',
                'description' => 'Program studi yang mempelajari kesehatan gigi dan mulut.',
                'min_score' => 80.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Kimia'],
                'preferred_subjects' => ['Biologi', 'Kimia'],
                'career_prospects' => 'Dokter Gigi, Peneliti, Konsultan Kesehatan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Veteriner',
                'description' => 'Program studi yang mempelajari kesehatan hewan dan pengobatan veteriner.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Kimia'],
                'preferred_subjects' => ['Biologi', 'Kimia'],
                'career_prospects' => 'Dokter Hewan, Peneliti, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Farmasi',
                'description' => 'Program studi yang mempelajari pengembangan dan pengelolaan obat-obatan.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Kimia'],
                'preferred_subjects' => ['Biologi', 'Kimia'],
                'career_prospects' => 'Apoteker, Peneliti, Quality Control, Konsultan Farmasi',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Gizi',
                'description' => 'Program studi yang mempelajari hubungan antara makanan dan kesehatan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Kimia'],
                'preferred_subjects' => ['Biologi', 'Kimia'],
                'career_prospects' => 'Ahli Gizi, Konsultan Nutrisi, Peneliti, Pengajar',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU SOSIAL (Lanjutan)
            [
                'major_name' => 'Pariwisata',
                'description' => 'Program studi yang mempelajari pengelolaan industri pariwisata.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Ekonomi', 'Bahasa Inggris Tingkat Lanjut'],
                'preferred_subjects' => ['Bahasa Inggris', 'Ekonomi', 'Bahasa Asing'],
                'career_prospects' => 'Manajer Pariwisata, Konsultan Pariwisata, Tour Guide, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Transportasi',
                'description' => 'Program studi yang mempelajari sistem dan manajemen transportasi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Ahli Transportasi, Konsultan Logistik, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Bioteknologi',
                'description' => 'Program studi yang mempelajari aplikasi teknologi dalam sistem biologis.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Matematika'],
                'preferred_subjects' => ['Biologi', 'Matematika'],
                'career_prospects' => 'Ahli Bioteknologi, Peneliti, Konsultan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Geografi',
                'description' => 'Program studi yang mempelajari permukaan bumi dan fenomena geografis.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Geografi', 'Matematika'],
                'preferred_subjects' => ['Fisika', 'Geografi', 'Matematika'],
                'career_prospects' => 'Ahli Geografi, Peneliti, Konsultan Lingkungan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Informatika Medis',
                'description' => 'Program studi yang mempelajari aplikasi teknologi informasi dalam bidang kesehatan.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi', 'Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Biologi', 'Matematika'],
                'career_prospects' => 'Ahli Informatika Medis, Konsultan IT Kesehatan, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Konservasi Biologi',
                'description' => 'Program studi yang mempelajari pelestarian keanekaragaman hayati.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Konservasi, Peneliti, Konsultan Lingkungan, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Teknologi Pangan',
                'description' => 'Program studi yang mempelajari pengolahan dan pengembangan produk pangan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Kimia', 'Biologi'],
                'preferred_subjects' => ['Kimia', 'Biologi'],
                'career_prospects' => 'Ahli Teknologi Pangan, Quality Control, Peneliti, Konsultan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sains Data',
                'description' => 'Program studi yang mempelajari analisis dan interpretasi data besar.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Data Scientist, Data Analyst, Konsultan, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Sains Perkopian',
                'description' => 'Program studi yang mempelajari ilmu dan teknologi kopi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Kopi, Peneliti, Konsultan, Entrepreneur',
                'is_active' => true,
            ],
            [
                'major_name' => 'Studi Humanitas',
                'description' => 'Program studi yang mempelajari aspek kemanusiaan dan budaya.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Antropologi', 'Sosiologi'],
                'preferred_subjects' => ['PPKn', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Peneliti Humaniora, Konsultan Budaya, Pengajar, Penulis',
                'is_active' => true,
            ],

            // RUMPUN ILMU: ILMU SOSIAL (Lanjutan)
            [
                'major_name' => 'Kesehatan Masyarakat',
                'description' => 'Program studi yang mempelajari peningkatan kesehatan masyarakat.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi', 'Sosiologi'],
                'career_prospects' => 'Ahli Kesehatan Masyarakat, Epidemiolog, Konsultan Kesehatan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kebidanan',
                'description' => 'Program studi yang mempelajari kesehatan ibu dan anak.',
                'min_score' => 75.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Bidan, Konsultan Kesehatan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Keperawatan',
                'description' => 'Program studi yang mempelajari asuhan keperawatan dan kesehatan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Perawat, Konsultan Kesehatan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Kesehatan',
                'description' => 'Program studi yang mempelajari berbagai aspek kesehatan manusia.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Biologi'],
                'preferred_subjects' => ['Biologi'],
                'career_prospects' => 'Ahli Kesehatan, Konsultan, Peneliti, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Informasi',
                'description' => 'Program studi yang mempelajari pengelolaan dan sistem informasi.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Matematika Tingkat Lanjut'],
                'preferred_subjects' => ['Matematika'],
                'career_prospects' => 'Ahli Informasi, Sistem Analis, Konsultan IT, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Hukum',
                'description' => 'Program studi yang mempelajari sistem hukum dan perundang-undangan.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi', 'Pendidikan Pancasila'],
                'preferred_subjects' => ['PPKn', 'Sosiologi'],
                'career_prospects' => 'Pengacara, Konsultan Hukum, Hakim, Pengajar',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Militer',
                'description' => 'Program studi yang mempelajari strategi dan taktik militer.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi'],
                'preferred_subjects' => ['PPKn', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Perwira Militer, Analis Keamanan, Konsultan Pertahanan',
                'is_active' => true,
            ],
            [
                'major_name' => 'Urusan Publik',
                'description' => 'Program studi yang mempelajari administrasi dan kebijakan publik.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['Sosiologi'],
                'preferred_subjects' => ['PPKn', 'Sosiologi', 'Antropologi'],
                'career_prospects' => 'Administrator Publik, Konsultan Kebijakan, Peneliti',
                'is_active' => true,
            ],
            [
                'major_name' => 'Ilmu Keolahragaan',
                'description' => 'Program studi yang mempelajari ilmu olahraga dan kebugaran.',
                'min_score' => 70.00,
                'max_score' => 100.00,
                'required_subjects' => ['PJOK', 'Biologi'],
                'preferred_subjects' => ['PJOK', 'Biologi'],
                'career_prospects' => 'Ahli Olahraga, Pelatih, Konsultan Kebugaran, Pengajar',
                'is_active' => true,
            ],
        ];

        foreach ($majors as $major) {
            MajorRecommendation::create($major);
        }

        $this->command->info('Major recommendations seeded successfully based on Ministerial Decree 102/M/2025!');
    }
}
